### ISSUE TITLE
can't filter on multiverse_id or id

### ISSUE THREAD

**Issue by quinten1333** [MagicTheGathering/mtg-sdk-python#11]
I can't filter a card on multiverse_id or id and filtering in combination with other traits  like color and subtype. Am I misreading something or is this not implemented?

https://api.magicthegathering.io/v1/cards/mutliverse_id or id works,but when i do https://api.magicthegathering.io/v1/cards?id=id or ?multiverse_id= multiverse_id it just gives all cards as result.

python:
query.where(multiverse_id=mid) and query.where(id=id) is also ignored.

I need this because i want to link my own database to yours by storing which user owns which card and letting your database doing the rest.

**Comment by adback03** [comment]
You can filter on a multiverse_id or id like this:

`card = Card.find(386616)`

The find method will retrieve a single card, and that card exactly by its ID.

**Comment by quinten1333** [comment]
yes and no. I want to give a set of cards to be queried and use your filtering. But if i would do this by name instead of id or mid the get url would be too long. This is probately why you haven't implemented it this way.

so what i'm trying to do is just not possible this way.

**Comment by adback03** [comment]
@quinten1333 You can now filter by `id` or `multiverseid`.
