### ISSUE TITLE
The foreign names of 'Unesh, Criosphinx Sovereign' are all in English

### ISSUE THREAD

**Issue by zjuguxi** [MagicTheGathering/mtg-sdk-python#12]
From HOU, number 52

**Comment by zjuguxi** [comment]
Chinese Simplified Unesh, Criosphinx Sovereign
Chinese Traditional Unesh, Criosphinx Sovereign
French Unesh, Criosphinx Sovereign
German Unesh, Criosphinx Sovereign
Italian Unesh, Criosphinx Sovereign
Japanese Unesh, Criosphinx Sovereign
Korean Unesh, Criosphinx Sovereign
Portuguese (Brazil) Unesh, Criosphinx Sovereign
Russian Unesh, Criosphinx Sovereign
Spanish Unesh, Criosphinx Sovereign

**Comment by adback03** [comment]
Please report this to https://github.com/mtgjson/mtgjson. They handle any data issues. Thanks!
