### ISSUE TITLE
using all() will get you all results, without caring about page

### ISSUE THREAD

**Issue by MrGreenTea** [MagicTheGathering/mtg-sdk-python#2]
Even if I use where(page=1).all(), I will get all results. When name is just a few characters (1-3), this will get absolutely out of hand and take forever. This might be wanted, but that all() ignores page keywords doesn't feel right...

**Comment by adback03** [comment]
Initially, that was the intended behavior. After thinking about it some more, I agree that it makes more sense to allow the user to only get a specific page if that's what they really want. I have implemented this behavior in  d4c7ce8, and will be part of the next package release.
