### ISSUE TITLE
What are the advantages of using `__new__` instead of `__init__`?

### ISSUE THREAD

**Issue by 0x326** [MagicTheGathering/mtg-sdk-python#21]
I noticed in #15 that we changed from `__init__` to `__new__` in classes like `Card` and `Set`. I was wondering what the advantage of this is?  It seems like `__init__` offers more utility over `__new__`, since IDEs can suggest class members and, with Python 3.6 type annotations, could even infer their type (see below)

```python
class Card:
    def __init__(self, response_dict=None):
        if response_dict is None:
            response_dict = {}
        self.name: str = response_dict.get('name')
        self.cmc: int = response_dict.get('cmc')
        # ...
```

**Comment by 0x326** [comment]
Or, if you wanted to use a native type, you could do something like this:

```python
from typing import NamedTuple


class Card(NamedTuple):
    name: str
    cmc: int

    # Optional functions here...


# Later...
card = Card(**response_dict)
```

**Comment by adback03** [comment]
Feel free to make a PR with the changes if __init__ is the preferred way. I'm not a huge python guy, so I personally can't speak to the benefits of one over the other :)
