### ISSUE TITLE
Question: Javascript port

### ISSUE THREAD

**Issue by raineorshine** [MagicTheGathering/mtg-sdk-python#3]
Hi! Any plans to port this to Javascript?

**Comment by adback03** [comment]
I can start looking into making a Javascript port in the near future. I'll leave this question open for now, and will provide updates as I am making the port.

Thanks for the interest in the project!

**Comment by raineorshine** [comment]
Thanks! I live in the Javascript and Nodejs world so that would be great.
If you create a repo and link me to it I might have the chance to
contribute with some pull requests.

I'm appreciating the polished presentation of your site. It's about time
that mtg started integrating some modern tech talent!

**Comment by raineorshine** [comment]
Started: https://github.com/raineorshine/mtg-sdk-javascript

- ES6
- Promise-based

Happy to transfer it to the [MagicTheGathering](https://github.com/MagicTheGathering) org :).

**Comment by adback03** [comment]
Awesome! Yeah, feel free to make a transfer request. I'm not sure if you lose access to the repo once it has been transferred, but if you do, I'll give you rights back to it.

**Comment by raineorshine** [comment]
`You don’t have admin rights to MagicTheGathering`

I had to transfer it to you directly. You can add it to the org and then add me as a collaborator if you'd like.

**Comment by adback03** [comment]
I have transferred the repo to the org and you should have write access. Thanks a lot!

**Comment by raineorshine** [comment]
Cool, thanks!
