### ISSUE TITLE
finding a card by multiverse_id returns a strange string

### ISSUE THREAD

**Issue by Tanchwa** [MagicTheGathering/mtg-sdk-python#35]
Just installed the sdk and have run into an issue seaching using the multiverse_id
the code 

```
card = Card.find(420830)
print(card)

```
returns the following string instead of information about the card

> <mtgsdk.card.Card object at 0x0000023A3E5190A0>

Other commands like getting sets, types, etc. seem to work fine. 
using python 3.9

**Comment by Realms-Reed** [comment]
That's the class Card from here:
https://github.com/MagicTheGathering/mtg-sdk-python/blob/master/mtgsdk/card.py

When you try to print an object that doesn't have a [\_\_str__ method](https://docs.python.org/3/reference/datamodel.html#object.__str__) the interpreter will instead print the name of the class and its memory address.

Try `print(dir(card))` to print a representation of the underlying dictionary.
