### ISSUE TITLE
Query for language

### ISSUE THREAD

**Issue by rafa-acioly** [MagicTheGathering/mtg-sdk-python#4]
I'm trying to use
`Card.where(language='portuguese').all()`

and i'm always geting empty list, i'v try as well:

`Card.where(language='russian').where(name=3).all()`

that are the same of

`https://api.magicthegathering.io/v1/cards?language=russian&name=3`

and i'm getting empty list too.

**Comment by adback03** [comment]
I believe we worked this out via discord. Let me know otherwise.

**Comment by rafa-acioly** [comment]
Yes, we solve through discord.
The problem was that the language portuguese is in different syntax.

`Card.where(language="Portuguese (Brazil)")`
